# languages.py
# This file contains a dictionary of language codes and their corresponding names and native names.

languages = {
    "aa": {"name": "Afar", "nativeName": "Qafar af"},
    "ab": {"name": "Abkhazian", "nativeName": "аҧсуа"},
    "ae": {"name": "Avestan", "nativeName": "avesta"},
    "af": {"name": "Afrikaans", "nativeName": "Afrikaans"},
    "ak": {"name": "Akan", "nativeName": "Akan"},
    "am": {"name": "Amharic", "nativeName": "አማርኛ"},
    "an": {"name": "Aragonese", "nativeName": "aragonés"},
    "ar": {"name": "Arabic", "nativeName": "العربية"},
    "as": {"name": "Assamese", "nativeName": "অসমীয়া"},
    "av": {"name": "Avaric", "nativeName": "авар мацӀ"},
    "ay": {"name": "Aymara", "nativeName": "aymar aru"},
    "az": {"name": "Azerbaijani", "nativeName": "azərbaycan dili"},
    "ba": {"name": "Bashkir", "nativeName": "башҡорт теле"},
    "be": {"name": "Belarusian", "nativeName": "беларуская"},
    "bg": {"name": "Bulgarian", "nativeName": "български"},
    "bh": {"name": "Bihari", "nativeName": "भोजपुरी"},
    "bi": {"name": "Bislama", "nativeName": "Bislama"},
    "bm": {"name": "Bambara", "nativeName": "bamanankan"},
    "bn": {"name": "Bengali", "nativeName": "বাংলা"},
    "bo": {"name": "Tibetan", "nativeName": "བོད་ཡིག"},
    "br": {"name": "Breton", "nativeName": "brezhoneg"},
    "bs": {"name": "Bosnian", "nativeName": "bosanski"},
    "ca": {"name": "Catalan", "nativeName": "català"},
    "ce": {"name": "Chechen", "nativeName": "нохчийн"},
    "ch": {"name": "Chamorro", "nativeName": "Chamoru"},
    "co": {"name": "Corsican", "nativeName": "corsu"},
    "cr": {"name": "Cree", "nativeName": "ᓀᐦᐃᔭᐍᐏᐣ"},
    "cs": {"name": "Czech", "nativeName": "čeština"},
    "cu": {"name": "Church Slavic", "nativeName": "церковнославянский"},
    "cv": {"name": "Chuvash", "nativeName": "чӑваш чӗлхи"},
    "cy": {"name": "Welsh", "nativeName": "Cymraeg"},
    "da": {"name": "Danish", "nativeName": "dansk"},
    "de": {"name": "German", "nativeName": "Deutsch"},
    "dv": {"name": "Divehi", "nativeName": "ދިވެހި"},
    "dz": {"name": "Dzongkha", "nativeName": "རྫོང་ཁ"},
    "ee": {"name": "Ewe", "nativeName": "Eʋegbe"},
    "el": {"name": "Greek", "nativeName": "Ελληνικά"},
    "en": {"name": "English", "nativeName": "English"},
    "eo": {"name": "Esperanto", "nativeName": "Esperanto"},
    "es": {"name": "Spanish", "nativeName": "español"},
    "et": {"name": "Estonian", "nativeName": "eesti"},
    "eu": {"name": "Basque", "nativeName": "euskara"},
    "fa": {"name": "Persian", "nativeName": "فارسی"},
    "ff": {"name": "Fulah", "nativeName": "Fulfulde"},
    "fi": {"name": "Finnish", "nativeName": "suomi"},
    "fj": {"name": "Fijian", "nativeName": "vosa Vakaviti"},
    "fo": {"name": "Faroese", "nativeName": "føroyskt"},
    "fr": {"name": "French", "nativeName": "français"},
    "fy": {"name": "Western Frisian", "nativeName": "Frysk"},
    "ga": {"name": "Irish", "nativeName": "Gaeilge"},
    "gd": {"name": "Scottish Gaelic", "nativeName": "Gàidhlig"},
    "gl": {"name": "Galician", "nativeName": "galego"},
    "gn": {"name": "Guarani", "nativeName": "Avañe'ẽ"},
    "gu": {"name": "Gujarati", "nativeName": "ગુજરાતી"},
    "gv": {"name": "Manx", "nativeName": "Gaelg"},
    "ha": {"name": "Hausa", "nativeName": "Hausa"},
    "he": {"name": "Hebrew", "nativeName": "עברית"},
    "hi": {"name": "Hindi", "nativeName": "हिन्दी"},
    "ho": {"name": "Hiri Motu", "nativeName": "Hiri Motu"},
    "hr": {"name": "Croatian", "nativeName": "hrvatski"},
    "ht": {"name": "Haitian", "nativeName": "Kreyòl ayisyen"},
    "hu": {"name": "Hungarian", "nativeName": "magyar"},
    "hy": {"name": "Armenian", "nativeName": "Հայերեն"},
    "hz": {"name": "Herero", "nativeName": "Otjiherero"},
    "ia": {"name": "Interlingua", "nativeName": "Interlingua"},
    "id": {"name": "Indonesian", "nativeName": "Bahasa Indonesia"},
    "ie": {"name": "Interlingue", "nativeName": "Interlingue"},
    "ig": {"name": "Igbo", "nativeName": "Asụsụ Igbo"},
    "ii": {"name": "Sichuan Yi", "nativeName": "ꆇꉙ"},
    "ik": {"name": "Inupiaq", "nativeName": "Iñupiaq"},
    "io": {"name": "Ido", "nativeName": "Ido"},
    "is": {"name": "Icelandic", "nativeName": "íslenska"},
    "it": {"name": "Italian", "nativeName": "italiano"},
    "iu": {"name": "Inuktitut", "nativeName": "ᐃᓄᒃᑎᑐᑦ"},
    "ja": {"name": "Japanese", "nativeName": "日本語"},
    "jv": {"name": "Javanese", "nativeName": "ꦧꦱꦗꦮ"},
    "ka": {"name": "Georgian", "nativeName": "ქართული"},
    "kg": {"name": "Kongo", "nativeName": "Kikongo"},
    "ki": {"name": "Kikuyu", "nativeName": "Gĩkũyũ"},
    "kj": {"name": "Kuanyama", "nativeName": "Kuanyama"},
    "kk": {"name": "Kazakh", "nativeName": "қазақ тілі"},
    "kl": {"name": "Kalaallisut", "nativeName": "kalaallisut"},
    "km": {"name": "Khmer", "nativeName": "ខ្មែរ"},
    "kn": {"name": "Kannada", "nativeName": "ಕನ್ನಡ"},
    "ko": {"name": "Korean", "nativeName": "한국어"},
    "kr": {"name": "Kanuri", "nativeName": "Kanuri"},
    "ks": {"name": "Kashmiri", "nativeName": "कश्मीरी / كشميري"},
    "ku": {"name": "Kurdish", "nativeName": "Kurdî"},
    "kv": {"name": "Komi", "nativeName": "коми кыв"},
    "kw": {"name": "Cornish", "nativeName": "Kernewek"},
    "ky": {"name": "Kirghiz", "nativeName": "кыргыз тили"},
    "la": {"name": "Latin", "nativeName": "latine"},
    "lb": {"name": "Luxembourgish", "nativeName": "Lëtzebuergesch"},
    "lg": {"name": "Ganda", "nativeName": "Luganda"},
    "li": {"name": "Limburgan", "nativeName": "Limburgs"},
    "ln": {"name": "Lingala", "nativeName": "Lingála"},
    "lo": {"name": "Lao", "nativeName": "ພາສາລາວ"},
    "lt": {"name": "Lithuanian", "nativeName": "lietuvių kalba"},
    "lu": {"name": "Luba-Katanga", "nativeName": "Tshiluba"},
    "lv": {"name": "Latvian", "nativeName": "latviešu valoda"},
    "mg": {"name": "Malagasy", "nativeName": "fiteny malagasy"},
    "mh": {"name": "Marshallese", "nativeName": "Kajin M̧ajeļ"},
    "mi": {"name": "Māori", "nativeName": "te reo Māori"},
    "mk": {"name": "Macedonian", "nativeName": "македонски"},
    "ml": {"name": "Malayalam", "nativeName": "മലയാളം"},
    "mn": {"name": "Mongolian", "nativeName": "монгол"},
    "mr": {"name": "Marathi", "nativeName": "मराठी"},
    "ms": {"name": "Malay", "nativeName": "Bahasa Melayu"},
    "mt": {"name": "Maltese", "nativeName": "Malti"},
    "my": {"name": "Burmese", "nativeName": "ဗမာစာ"},
    "na": {"name": "Nauru", "nativeName": "Dorerin Naoero"},
    "nb": {"name": "Norwegian Bokmål", "nativeName": "Bokmål"},
    "nd": {"name": "North Ndebele", "nativeName": "isiNdebele"},
    "ne": {"name": "Nepali", "nativeName": "नेपाली"},
    "ng": {"name": "Ndonga", "nativeName": "Owambo"},
    "nl": {"name": "Dutch", "nativeName": "Nederlands"},
    "nn": {"name": "Norwegian Nynorsk", "nativeName": "Nynorsk"},
    "no": {"name": "Norwegian", "nativeName": "Norsk"},
    "nr": {"name": "South Ndebele", "nativeName": "isiNdebele"},
    "nv": {"name": "Navajo", "nativeName": "Diné bizaad"},
    "ny": {"name": "Chichewa", "nativeName": "chiCheŵa"},
    "oc": {"name": "Occitan", "nativeName": "occitan"},
    "oj": {"name": "Ojibwa", "nativeName": "Anishinaabemowin"},
    "om": {"name": "Oromo", "nativeName": "Afaan Oromoo"},
    "or": {"name": "Oriya", "nativeName": "ଓଡ଼ିଆ"},
    "os": {"name": "Ossetian", "nativeName": "ирон æвзаг"},
    "pa": {"name": "Punjabi", "nativeName": "ਪੰਜਾਬੀ"},
    "pi": {"name": "Pali", "nativeName": "पाऴि"},
    "pl": {"name": "Polish", "nativeName": "polski"},
    "ps": {"name": "Pashto", "nativeName": "پښتو"},
    "pt": {"name": "Portuguese", "nativeName": "português"},
    "qu": {"name": "Quechua", "nativeName": "Runa Simi"},
    "rm": {"name": "Romansh", "nativeName": "rumantsch"},
    "rn": {"name": "Rundi", "nativeName": "Ikirundi"},
    "ro": {"name": "Romanian", "nativeName": "română"},
    "ru": {"name": "Russian", "nativeName": "русский"},
    "rw": {"name": "Kinyarwanda", "nativeName": "Ikinyarwanda"},
    "sa": {"name": "Sanskrit", "nativeName": "संस्कृतम्"},
    "sc": {"name": "Sardinian", "nativeName": "sardu"},
    "sd": {"name": "Sindhi", "nativeName": "سنڌي"},
    "se": {"name": "Northern Sami", "nativeName": "Davvisámegiella"},
    "sg": {"name": "Sango", "nativeName": "yângâ tî sängö"},
    "si": {"name": "Sinhala", "nativeName": "සිංහල"},
    "sk": {"name": "Slovak", "nativeName": "slovenčina"},
    "sl": {"name": "Slovenian", "nativeName": "slovenščina"},
    "sm": {"name": "Samoan", "nativeName": "gagana fa'a Samoa"},
    "sn": {"name": "Shona", "nativeName": "chiShona"},
    "so": {"name": "Somali", "nativeName": "Soomaaliga"},
    "sq": {"name": "Albanian", "nativeName": "Shqip"},
    "sr": {"name": "Serbian", "nativeName": "српски"},
    "ss": {"name": "Swati", "nativeName": "SiSwati"},
    "st": {"name": "Southern Sotho", "nativeName": "Sesotho"},
    "su": {"name": "Sundanese", "nativeName": "Basa Sunda"},
    "sv": {"name": "Swedish", "nativeName": "svenska"},
    "sw": {"name": "Swahili", "nativeName": "Kiswahili"},
    "ta": {"name": "Tamil", "nativeName": "தமிழ்"},
    "te": {"name": "Telugu", "nativeName": "తెలుగు"},
    "tg": {"name": "Tajik", "nativeName": "тоҷикӣ"},
    "th": {"name": "Thai", "nativeName": "ไทย"},
    "ti": {"name": "Tigrinya", "nativeName": "ትግርኛ"},
    "tk": {"name": "Turkmen", "nativeName": "türkmen dili"},
    "tl": {"name": "Tagalog", "nativeName": "Wikang Tagalog"},
    "tn": {"name": "Tswana", "nativeName": "Setswana"},
    "to": {"name": "Tonga", "nativeName": "faka Tonga"},
    "tr": {"name": "Turkish", "nativeName": "Türkçe"},
    "ts": {"name": "Tsonga", "nativeName": "Xitsonga"},
    "tt": {"name": "Tatar", "nativeName": "татарча"},
    "tw": {"name": "Twi", "nativeName": "Twi"},
    "ty": {"name": "Tahitian", "nativeName": "Reo Tahiti"},
    "ug": {"name": "Uighur", "nativeName": "ئۇيغۇرچە"},
    "uk": {"name": "Ukrainian", "nativeName": "українська"},
    "ur": {"name": "Urdu", "nativeName": "اردو"},
    "uz": {"name": "Uzbek", "nativeName": "o‘zbek tili"},
    "ve": {"name": "Venda", "nativeName": "Tshivenda"},
    "vi": {"name": "Vietnamese", "nativeName": "Tiếng Việt"},
    "vo": {"name": "Volapük", "nativeName": "Volapük"},
    "wa": {"name": "Walloon", "nativeName": "walon"},
    "wo": {"name": "Wolof", "nativeName": "Wollof"},
    "xh": {"name": "Xhosa", "nativeName": "isiXhosa"},
    "yi": {"name": "Yiddish", "nativeName": "ייִדיש"},
    "yo": {"name": "Yoruba", "nativeName": "Yorùbá"},
    "za": {"name": "Zhuang", "nativeName": "Saɯ cueŋƅ"},
    "zh": {"name": "Chinese", "nativeName": "中文"},
    "zu": {"name": "Zulu", "nativeName": "isiZulu"},
}

